### ISSUE TITLE
Check the exit status using os.WIFEXITED()

### ISSUE THREAD

**Issue by linsalrob** [metageni/SUPER-FOCUS#1]
You should check the exit status of external programs (e.g. rapsearch, diamond, etc) using [os.WIFEXITED](https://docs.python.org/3/library/os.html#os.WIFEXITED)() and [os.WEXITSTATUS](https://docs.python.org/3/library/os.html#os.WEXITSTATUS)(). If the program terminated abnormally you should not continue.

**Comment by metageni** [comment]
The latest version of the program should handle it already.
