### ISSUE TITLE
"Uncompressing db failed" superfocus_downloadDB.py blast

### ISSUE THREAD

**Issue by bashirhamidi** [metageni/SUPER-FOCUS#12]
Getting the below error due to superfocus_downlaodDB.py not finding the downloaded db.

> (super-focus) [x@y ~]$ `superfocus_downloadDB.py blast `
> Downloading DB
> --2018-07-13 14:40:58--  http://edwards.sdsu.edu/superfocus/downloads/db.zip
> Resolving edwards.sdsu.edu... 130.191.93.70
> Connecting to edwards.sdsu.edu|130.191.93.70|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 3527705740 (3.3G) [application/zip]
> Saving to: "db.zip"
> 
> 100%[=======================================================================================>] 3,527,705,740 39.3M/s   in 49m 22s 
> 
> 2018-07-13 15:30:20 (1.14 MB/s) - "db.zip" saved [3527705740/3527705740]
> 
> 
> Uncompressing DB
> unzip:  cannot find or open db/db.zip, db/db.zip.zip or db/db.zip.ZIP.
> mv: accessing `db/': Not a directory
> rm: cannot remove `db/db.zip': Not a directory
> 
> Joining files
> Traceback (most recent call last):
>   File "/home/bah29/packages/anaconda3/envs/super-focus/bin/superfocus_downloadDB.py", line 119, in <module>
>     main()
>   File "/home/bah29/packages/anaconda3/envs/super-focus/bin/superfocus_downloadDB.py", line 108, in main
>     donwloadDBnFormat(aligners)
>   File "/home/bah29/packages/anaconda3/envs/super-focus/bin/superfocus_downloadDB.py", line 46, in donwloadDBnFormat
>     for cluster in os.listdir("db/clusters/")
> OSError: [Errno 20] Not a directory: 'db/clusters/'

The db is still accessible in the downloaded directly. I have unzipped db as such:
`(super-focus) [x@y ~]$ unzip "db" -d db2/`
**Do I need to move the unzipped db to a particular directory?**

**Comment by metageni** [comment]
we have been working to move the tool into bioconda, and it looks like the download script is not working correctly when installing the tool with conda.

quick solution: `cd /home/bah29/packages/anaconda3/envs/super-focus/bin/` (which i believe is where conda put the super-focus scripts) and then `superfocus_downloadDB.py blast`

I will work on the fix in the mean time - sorry about that.
