### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by corburn** [metageni/SUPER-FOCUS#15]
Hi, could you restore the repository license removed in commit cd4bb12ba5ec5449520bf48ed5dfc130d169f0e5? I'm updating the bioconda recipe and the build failed because the file was not found.

Thanks for tagging the release!

**Comment by metageni** [comment]
Hi @corburn Thanks for working on it. I have added what you asked and other things. Also, I updated the release. 

This version of the tool just passed by a big refactoring. The big one: It now uses Python3. Hopefully, it won't give you much more work.

Thanks for working on it.

best
