### ISSUE TITLE
Plotting code underscores

### ISSUE THREAD

**Issue by zkstewart** [metageni/SUPER-FOCUS#2]
Hi,

I ran into an issue when trying to run the R scripts. At the data processing stage, the script looks for files with a pattern that differs to the output SUPER-FOCUS provided me. On this line

`list.files(opt$sf_dir, pattern="_____results__all_levels_and_function.xls")[[1]]`

there appears to be too many underscores at the front, as the output files I obtained only have two underscores after the project name. From reading through the superfocus.py file, it looks like if you run a single reads file your output will have two underscores, but if you run a directory with multiple reads files then an extra 3 get added during the "for target in targets" loop. 

Thanks,
Zac.

**Comment by metageni** [comment]
Sorry. SUPER-FOCUS does not support the scripts for plotting anymore
