### ISSUE TITLE
Error when running download_DB command - wget command

### ISSUE THREAD

**Issue by vinisalazar** [metageni/SUPER-FOCUS#20]
Hi,

I was trying to use your program. I installed all the dependencies and had both `blast` and `diamond` installed. However, when I ran the `superfocus_downloadDB -a <aligner>` command for either aligner, I got an error, and the cause for it was not having `wget` installed.

I'm installing SUPER-FOCUS on a Mac computer, therefore `wget` is not installed by default. The default command for downloading in OS X is `curl`.

My problem was easily solved by installing `wget` command with `brew`. 

However, to prevent this problem to future Mac users, I see some potential solutions:

1. replacing `wget` with `curl` in the `superfocus_downloadDB` script.
2. adding a statement like `sys.platform` or `os.uname()` to check the operating system and use the appropriate command.
3. Incrementing the error message to say something like "Do you have `wget` installed? If not, you can install it with `brew`." (Least recommended).

I'd be happy to contribute with a PR for that.

I also submitted #19 which should help with installation.

bw,

V

**Comment by metageni** [comment]
@vinisalazar thanks for the suggestion. I will include it in the next release.

**Comment by metageni** [comment]
@vinisalazar I have merged the suggested changes. Thanks!

**Comment by vinisalazar** [comment]
happy to help. I hope to make time for further contributions even if they are just issues 🙂
