### ISSUE TITLE
Blast error

### ISSUE THREAD

**Issue by ghost** [metageni/SUPER-FOCUS#3]
I am getting this blast error. I used superfocus__downloadDB.py blast, first then:

superfocus.py -q rare/ -dir 60.4superfocus -t 36 -a blast

1) Aligning sequences in rare//033.fastq against DB_98 using blast
Error: NCBI C++ Exception:
    T0 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_350334_130.14.22.10_9008__PrepareRelease_Linux64-Centos_1481139955/c++/compilers/unix/../../src/objtools/readers/fasta.cpp", line 2428: Error: CFastaReader: Near line 1, there's a line that doesn't look like plausible data, but it's not marked as defline or comment. (m_Pos = 1)

The fastq files look fine, e.g. head of 033.fastq:
@MG00HS17:796:HHJJYBCXX:1:1101:1988:2000 1:N:0:CCGTCC
NTTCCCGAACGCAGTGCATCTTGTTGTAAATATTTTACTACATACGATTTTGAGTATGGCTTCCAGTTGTTCTGTACAGAATATGGATCGACATATTTGCATCTTCTCATTATGTCCTCAGCTTTGTTGCTCAATTCTTTTAATACAGCCG
+
#<DDDHIIIIIIIIIIIIIIIGHIIIIIIIIIIIIIIGIIIIHIIIIIIIIIIIHHHHHIIIIHIHHGH1DGHHHHIIIGHIIHIEHGHC=?HIHEHHF?HGHIIIIIIIIIIIIIGIIGGIIIIIIIHHH1CCEHCHIIHIHIIIIGHI<
@MG00HS17:796:HHJJYBCXX:1:1101:1988:2000 2:N:0:CCGTCC
CACAAATTTATACGCAATACCATATCGAAACTGATAGGATATAAGAAAATAACCATCGGCATTGCATTCGCAATCCTTATTCTATGCATTGCCGGAATGGGAAAAGTAAAAAACTTGTTCTTTCCAGATTTCGACTATAAGCAATATGTGA
+
D@DDDIIIIIIIIHIIIIIIHIIIIGIIIIIHIIIIIGIIIIHGHIIIIIIIIIIIIIHDHHHGHHIIHIIIIHIGIHIIHIGGIIIHIHCH1EHHHGHHHHGHIHIHIIIHHIHHIHIIH?CDGHCHHHHGIIIIIHHHHEGHHHHGEH?

**Comment by ghost** [comment]
I think perhaps you can't use fastq input with blast... a note is required in the guide which at the moment says you can use fastq or fasta.

**Comment by metageni** [comment]
Yeah. Sorry I just saw your comment now. I have to turn on my git notification. I will edit the README
