### ISSUE TITLE
Re-run super-focus using existing alignments

### ISSUE THREAD

**Issue by ehj000** [metageni/SUPER-FOCUS#30]
Hi,
I have just finished a large super-focus job where the query counts have been normalized based on number of hits (default setting). I wonder if I can re-run super-focus using the existing alignment files with different settings to produce non-normalized counts? 

The previous job took three days producing 1.5 TB alignments, so I would rather not do the alignment again.
Thanks you
Erik

**Comment by metageni** [comment]
Hi @ehj000, currently it is not possible, but I can possibly add this function to it. It is the end of the year so it will take me some time - sorry.
