### ISSUE TITLE
Database not found

### ISSUE THREAD

**Issue by blancaverag** [metageni/SUPER-FOCUS#5]
I am having some issues trying to run SUPER-FOCUS. 
I get this error when running it, despite having the databases:

python superfocus.py -q prot.faa -dir superfocus_smo/ -o smo -ml 50 -p 1 -a diamond -fast 1
SUPER-FOCUS: A tool for agile functional analysis of shotgun metagenomic data
     -diamond DB_98 database was not found. Please first run python superfocus__downloadDB.py diamond or choose a DB which exists

I have already tried to rerun superfocus__downloadDB.py and specifically set another database with -db option without luck.

Any idea of what the issue might be? 
Thank you in advance

**Comment by blancaverag** [comment]
It seems to be working with rapsearch. Do I need to set something related to the database differently so I can use diamond?

**Comment by metageni** [comment]
`Do I need to set something related to the database differently so I can use diamond?`

No, installing the aligner should be all you need.
