### ISSUE TITLE
rapsearch database cannot open

### ISSUE THREAD

**Issue by s4251484** [metageni/SUPER-FOCUS#50]
Hi @metageni i'm receiving this error when i try running superfocus with rapsearch database, but it runs perfectly when i run it with diamond! strange~

Queries are nucleotide sequences in fasta format
Can not open the database file
Please check the file name
>>>Main END
Time used: 0 min (0.0 hours)
[2019-04-13 18:12:43,801 - INFO]    Parsing Alignments
Traceback (most recent call last):
  File "/gpfs1/scratch/30days/s4251484/condaenv/qctrim/bin/superfocus", line 11, in <module>
    load_entry_point('superfocus==0.0.0', 'console_scripts', 'superfocus')()
  File "/gpfs1/scratch/30days/s4251484/condaenv/qctrim/lib/python3.7/site-packages/superfocus_app/superfocus.py", line 342, in main
    del_alignments)
ValueError: not enough values to unpack (expected 2, got 0)

i'm wondering is it because of this difference (see attachment) between rapsearch and diamond in the downloadDB.py? where "format(dbname, WORK_DIRECTORY, dbname)" are at different row???

appreciate your help! thank you!
<img width="828" alt="Screen Shot 2019-04-13 at 6 24 00 pm" src="https://user-images.githubusercontent.com/42083931/56076934-9c3dcd00-5e19-11e9-99a9-71df2577b730.png">

These are the files in my lib/python3.7/site-packages/superfocus_app/db/static/rapsearch2 folder - please let me know if they are named incorrectly. thank you.
<img width="394" alt="Screen Shot 2019-04-13 at 6 41 38 pm" src="https://user-images.githubusercontent.com/42083931/56077134-e45def00-5e1b-11e9-8c8c-6e534a7daef4.png">

**Comment by s4251484** [comment]
Sorry @metageni  please close this issue. turn out that the info file was renamed, hence the script couldnt work.

**Comment by metageni** [comment]
@s4251484 No problem. `prerapsearch` is the tool to format the database and `rapsearch` is the aligner - that is why the confusion.
