### ISSUE TITLE
Issues with Excel-based output

### ISSUE THREAD

**Issue by ctseto** [metageni/SUPER-FOCUS#51]
Getting errors with opening xls outputs (eg output_binning.xls) on Office 2013 on a work machine:
"The file format and extension of output_binning.xls don't match. The file could be corrupted or unsafe..."
Ignoring the cautionary message it appears to open just fine. Similarly, opening these files in R with readxl::read_excel() appears to generate error messages; but unsure if the latter is related to the former.

**Comment by metageni** [comment]
Please rename the file to `*.csv` and open on `excel`. Or just say `Yes` when you see the message you got.

**Comment by ctseto** [comment]
I feel pretty stupid for not running head earlier and seeing that it was plain-text. But at least it's something that is pretty easy to resolve, thanks!
