### ISSUE TITLE
not enough values to unpack error

### ISSUE THREAD

**Issue by bcpd** [metageni/SUPER-FOCUS#53]
Dear all,

Thank you for this great tool. After smoothly running 65 fastq files using -a diamond and -db DB_100, I get the following error:

File "/usr/bin/miniconda3/lib/python3.6/site-packages/superfocus_app/superfocus.py", line 342, in main
del_alignments)
ValueError: not enough values to unpack (expected 2, got 0)

This does not appear to be a disk space issue, as I have 430GB of space available, nor is it a memory deficit, as I have 256GB of RAM available. Any help would be greatly appreciated.

**Comment by metageni** [comment]
Sorry for the late answer. Did you figure it out? Probably one of the FASTQs is too small and did not generate any alignments.

Let me know what you found, so I can fix the bug, if any.

Best

**Comment by bcpd** [comment]
Hi Geni,
Thank you for your reply. I cannot say for sure if the size of the alignment is causing the issue, but I just had the same problem with another dataset (the one giving me problems ended up running fine). If what you say is true, then it would be great if superfocus could skip the small files and run to completion.
Thanks very much.

**Comment by metageni** [comment]
Do you still have the command line you ran? I recently fixed a bug related to this.

Best

**Comment by bcpd** [comment]
Hi Geni,

This is the command (excluding or including the -d makes no difference):
superfocus -q /folder/ -dir /folder/ -db DB_100 -a diamond -t 8 -d 

Also, a negative control with ~1000 reads ran fine, so size does not appear to be an issue.

**Comment by metageni** [comment]
I see. Thanks for sharing it.
