### ISSUE TITLE
Description on functional profiles

### ISSUE THREAD

**Issue by bishav6708** [metageni/SUPER-FOCUS#56]
What is the difference between the 'Phages, Prophages, Transposable elements' and 'Phages, Prophages, Transposable elements, Plasmids'. How are 'Phages, Prophages, Transposable elements' incorporated in the later one? Does this indicate anything for the horizontal gene transfer? 
Can you refer to any literature for some detail description of each function?

**Comment by metageni** [comment]
Hi @bishav6708 I think this is a question to the SEED team. I'm sorry for not having an answer.
