### ISSUE TITLE
"FOCUS is not avaliable on this version"

### ISSUE THREAD

**Issue by cbjurnemark** [metageni/SUPER-FOCUS#58]
Hi, I am trying to run SUPER-FOCUS for the first time and encountered an error. 

When running SUPER-FOCUS using command: 
 
```
superfocus \
-q input/ \
-m 1 \
-dir output/ \
-t 16 \
-db DB_100 \
-a diamond
```

I get the following error message: 

`FOCUS: Running FOCUS is not avaliable on this version. Please see https://github.com/metageni/FOCUS on how to run it`

I have version SUPER-FOCUS 0.34 and according to the wiki I understand it as I should be able to run FOCUS using SUPER-FOCUS. 

Is the newest version (0.34) not able to run FOCUS? 
And if so, how do I input the output from FOCUS when running it separately? 

I appreciate all the help I can get. 

Best, 
Caroline

**Comment by metageni** [comment]
Hi @cbjurnemark That is correct. FOCUS was removed from SUPER-FOCUS on the latest version. However, you can still un FOCUS separated if you want. It should be easy to install and run.

I intend to put it back in the next release - currently working on a bug.

**Comment by cbjurnemark** [comment]
Thank you for the quick reply! 

Do I put the output from FOCUS in the same input folder as the fastq files or does that have to be handled differently? I did not find any information about that part.

**Comment by metageni** [comment]
As I removed FOCUS as part of the SUPER-FOCUS workflow, you don't need to use the FOCUS output as SUPER-FOCUS input. 

The only reason you should run FOCUS separately is if you need the taxonomic analysis for whatever you are doing, but you don't need to input this to SUPER-FOCUS. 

If you are only interested in only the functional analysis running only SUPER-FOCUS is enough.

**Comment by cbjurnemark** [comment]
Ok I understand! Thanks for the clarification!
