### ISSUE TITLE
R duplicated levels

### ISSUE THREAD

**Issue by ehj000** [metageni/SUPER-FOCUS#6]
Hi,
First of all thanks for a very nice tool.

I am not able to run superfocus_plots.sh on the sample files that are provided with the tool. It seems to be issues with the duplicated levels in factors in R:

[2017-08-29 21:08:57]    *****Starting plotting scripts!*****
[2017-08-29 21:08:57]    Note: verbose flag was not set.
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [15] is duplicated
Calls: factor
Execution halted
./superfocus_plots.sh: line 107: error: command not found
[2017-08-29 21:09:00]    *****Completed!*****

Is there a solution to this?
Kindly regards
Erik Hjerde

**Comment by metageni** [comment]
Sorry. SUPER-FOCUS does not support the scripts for plotting anymore
