### ISSUE TITLE
Please, help => ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by chulghim** [metageni/SUPER-FOCUS#61]
I installed latest version super-focus from github.

Python version 3.7.3
diamon version 0.931

python ./superfocus_app/superfocus.py -q in -dir out -a diamond -t 20
...
....
Loading query sequences...  [0s]
Closing the input file...  [0s]
Closing the output file...  [0.423s]
Closing the database file...  [0s]
Deallocating taxonomy...  [0s]
Total time = 1746.95s
Reported 224525228 pairwise alignments, 224526338 HSPs.
13685926 queries aligned.
diamond v0.9.31.132 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 28
Loading subject IDs... [2020-06-18 04:26:52,727 - INFO]    Parsing Alignments
Traceback (most recent call last):
  File "./superfocus_app/superfocus.py", line 375, in <module>
  File "./superfocus_app/superfocus.py", line 342, in main
    temp_header = ["Subsystem Level 1", "Subsystem Level 2", "Subsystem Level 3", "Function"] + header_files
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by metageni** [comment]
@chulghim Could you please install it using one of the methods described here (https://github.com/metageni/SUPER-FOCUS#installation). It will add the tool to your path - it makes a big difference.

Also, did you format the database to work with DIAMOND using (https://github.com/metageni/SUPER-FOCUS#database)?

Let me know
