### ISSUE TITLE
single-file query no longer working?

### ISSUE THREAD

**Issue by ModelMEMS** [metageni/SUPER-FOCUS#69]
I read in older documentation that focus had an option -m 0 to use a single fasta as input (rather than a directory). However, that appears to no longer work, as I get the error:

NotADirectoryError: [Errno 20] Not a directory: 'my_fasta.fa'

**Comment by metageni** [comment]
Sorry for taking too long to get back to you. You are correct; the latest version of the tool only takes a directory.
