### ISSUE TITLE
Slow DB download

### ISSUE THREAD

**Issue by ghost** [metageni/SUPER-FOCUS#7]
Only getting about 25 - 100 kB/s from edwards.sdsu.edu/superfocus/downloads/db.zip from Australia.
Are there any mirror sites available?
Thanks,

Theo

**Comment by ghost** [comment]
I should add that the download is also very intermittent.. 15 secs no transfer then sharktooth peak for 10 secs. Otherwise my connection is ok so I assume its the server? Thanks.

**Comment by metageni** [comment]
Hi there, I hope you were able to download the database. At this point we don't plan to have a mirror of the database.
