### ISSUE TITLE
version doesn't work

### ISSUE THREAD

**Issue by linsalrob** [metageni/SUPER-FOCUS#76]
The `-v` option does not inform us of the version:

Install from conda, then 

```bash
$ superfocus -v
SUPER-FOCUS 0.0.0
```

**Comment by metageni** [comment]
Thanks. I will this out for the next release; it seems to work with pip.

**Comment by linsalrob** [comment]
You probably need to add these two lines to your `host:` section in your [bioconda/super-focus/meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/super-focus/meta.yaml) file:

```
    - setuptools >=38.6.0
    - setuptools_scm
```

**Comment by metageni** [comment]
@linsalrob : was this fixed with your bioconda PR? thanks

**Comment by linsalrob** [comment]
Yes, all fixed. It required `setuptools_scm` in the `meta.yaml`
