### ISSUE TITLE
can't download database

### ISSUE THREAD

**Issue by ncanaless** [metageni/SUPER-FOCUS#78]
Hi i've been trying to download the SUPER-FOCUS database and getting this error:

$wget edwards.sdsu.edu/superfocus/downloads/db.zip
...
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2022-03-15 12:26:16 ERROR 503: Service Temporarily Unavailable.

is there any solution to this problem? thanks in advance

**Comment by metageni** [comment]
@linsalrob: Any idea what happened to the server?

**Comment by metageni** [comment]
@ncanaless: I'm checking with @linsalrob what's up. Depending what happened, i will move the db somewhere else. thanks

**Comment by ncanaless** [comment]
that would be amazing, thank you so much

**Comment by metageni** [comment]
I'm moving it to another server. stay tuned.

**Comment by metageni** [comment]
@ncanaless: I'm sorry; we are still working on it. For now, it lives here --- https://drive.google.com/file/d/1jTo2e5UQLkEItRrgTJhOhXZAAUV-ACd7/view?usp=sharing

I will be moving it to a more appropriate location soon.

**Comment by ncanaless** [comment]
Hi @metageni , i was able to download the database, thanks for the quick response, but now i'm getting another issue trying to format it. (i downloaded and unziped following the manual instructions)
**superfocus_downloadDB -i clusters/ -a diamond -c 90,95**
Traceback (most recent call last):
  File "/home/metagroup/anaconda3/envs/metaphlan/bin/superfocus_downloadDB", line 10, in <module>
    sys.exit(main())
  File "/home/metagroup/anaconda3/envs/metaphlan/lib/python3.7/site-packages/superfocus_app/superfocus_downloadDB.py", line 158, in main
    db_dir_exists = Path(args.db_dir).exists() and Path(args.db_dir).is_dir()
  File "/home/metagroup/anaconda3/envs/metaphlan/lib/python3.7/pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/metagroup/anaconda3/envs/metaphlan/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/metagroup/anaconda3/envs/metaphlan/lib/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I'm using superfocus in a conda enviroment, with python 3.7 as extra information

**Comment by metageni** [comment]
I see. Sorry about it. it was a bug introduced when there was a PR to introduce an alternative directory for the db. 

The slowest path to fix this, for now, is to pass a path when formating the database to where it is going to live 


`superfocus_downloadDB -i clusters/ -a diamond -c 90,95 -db_dir PATH_DB`

and when running superfocus, passing the db at `--alternate_directory`. 

I will fix the bug now, and it should be live on bioconda the change tomorrow. Sorry about that.

**Comment by metageni** [comment]
here is the fix for the bug for reference https://github.com/metageni/SUPER-FOCUS/pull/79

**Comment by ncanaless** [comment]
thanks a lot for your help, i think now i'm able to run the program, again thank you so much

**Comment by SergeyBaikal** [comment]
> I see. Sorry about it. it was a bug introduced when there was a PR to introduce an alternative directory for the db.
> 
> The slowest path to fix this, for now, is to pass a path when formating the database to where it is going to live
> 
> `superfocus_downloadDB -i clusters/ -a diamond -c 90,95 -db_dir PATH_DB`
> 
> and when running superfocus, passing the db at `--alternate_directory`.
> 
> I will fix the bug now, and it should be live on bioconda the change tomorrow. Sorry about that.

That's the way a command should be.
`superfocus_downloadDB -i /clusters/ -a rapsearch -c 100 -d /SuperFocus/superfocus_app/db/static/rapsearch2/`
In general, the description of the program is strange on the main page. And it is not clear when the database was last updated. For example, you can download [db.zip](https://drive.google.com/file/d/1jTo2e5UQLkEItRrgTJhOhXZAAUV-ACd7/view?usp=sharing) only if you read the comments, but on the main page of the program is strange.
