### ISSUE TITLE
Can´t download databases

### ISSUE THREAD

**Issue by JennsiS** [metageni/SUPER-FOCUS#81]
Is still giving maintenance for this tool? I would like to use it but I can't download the databases. Are the links still working?
Everytime i try to download any of the databases described in the installation documentation, the request time out.

**Comment by metageni-twist** [comment]
Hi Jenniffer, please download it here

https://drive.google.com/file/d/1jTo2e5UQLkEItRrgTJhOhXZAAUV-ACd7/view?usp=sharing

**Comment by JennsiS** [comment]
Thanks for answering! I managed to download the database with the link you provide, however, when I run the indicated command superfocus_downloadDB -i <clusters_folder> -a <aligner> -c <clusters>
 
It gives me the following error.
![imagen](https://user-images.githubusercontent.com/42972809/197913574-112a3fb5-5c5d-49f0-b6d9-7f49db9fdc7f.png)

Is there any other way to configure this database?

**Comment by JennsiS** [comment]
Thanks for answering! I managed to download the database with the link you provide, however, when I run the indicated command superfocus_downloadDB -i <clusters_folder> -a -c

It gives me the following error.
![imagen](https://user-images.githubusercontent.com/42972809/197914108-c696307e-2022-4734-b514-7c042a37ba9e.png)


Is there any other way to configure this database? @metageni-twist

**Comment by linsalrob** [comment]
I have updated the URLs for the database downloads to a new location. All
files should be available.

Rob

**Comment by linsalrob** [comment]
The prebuilt databases should be available as zip files now and the
instructions for installing them are here:

https://github.com/metageni/SUPER-FOCUS/blob/master/README.md#downloading-prebuilt-databases

Rob

**Comment by JennsiS** [comment]
Thank you, finally i was able to use the tool. I´m very satisfied with the results. I´m very grateful for your quick response.
