### ISSUE TITLE
diamond v2.0.xx

### ISSUE THREAD

**Issue by bcpd** [metageni/SUPER-FOCUS#82]
Hello all - I wanted to make super-focus is compatible with diamond v2, as the the following link (https://github.com/bbuchfink/diamond/wiki/5.-Advanced-topics#database-format-versions) seems to suggest it is. Thanks very much.

**Comment by metageni-twist** [comment]
i have never tried it. Any thoughts? @linsalrob

**Comment by linsalrob** [comment]
There are diamond version 2 databases already available:
https://cloudstor.aarnet.edu.au/plus/s/ABAbFgoUow9Swpi

Rob

**Comment by bcpd** [comment]
Great -- thank you for your reply. I will close the issue for now.
