### ISSUE TITLE
Could not concatenate clusters at level 90

### ISSUE THREAD

**Issue by wittney-m** [metageni/SUPER-FOCUS#83]
I am attempting to format the diamond databases that I have already downloaded. Currently the databases are uncompressed in folders with the following paths
- /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/90_clusters
- /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/95_clusters
- /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/98_clusters
- /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/100_clusters

The example of the file listed in each folder is 98_clusters.db.dmnd, which is downloaded directly from the github instructions. When I run the following command
 superfocus_downloadDB -a diamond -c 90,95,98,100 -i /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/

I receive this error:
Concatenating /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/90_clusters/*.faa > 90_clusters.fasta
cat: /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/90_clusters/*.faa: No such file or directory
[2023-10-08 20:07:53,087 - ERROR] Could not concatenate clusters at level 90

How do I format the databases with download_DB?

**Comment by metageni-twist** [comment]
hi - i tested and worked fine on my side. Could you please list the files you have here ` /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/static/diamond/90_clusters/`.

**Comment by wittney-m** [comment]
Hi,

When I unzipped the file from [here](https://cloudstor.aarnet.edu.au/plus/s/YCv7r8RnMXSQICb/download), which was the diamond version 3 90 cluster, the only file that is present is 90_clusters.db.dmnd. Is this incorrect?

**Comment by metageni-twist** [comment]
I see. So you downloaded the databases formatted already.

Please see https://github.com/metageni/SUPER-FOCUS#downloading-prebuilt-databases in the DIAMOND section. Pretty much now you need to move the database files into the correct database directory.
