### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by wittney-m** [metageni/SUPER-FOCUS#84]
Hi I ran the command below:

source activate super-focus

conda env config vars set SUPERFOCUS_DB=/home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/

superfocus --threads 8 -q /home/wdmays/SHASTA/fastq_files/zr12348_1_R1.fastq -q /home/wdmays/SHASTA/fastq_files/zr12348_2_R1.fastq  -dir /home/wdmays/SHASTA/superfocus_output_diamond -o SHASTA_diamond -a diamond 

This is the output error that I am receiving

WARNING: overwriting environment variables set in the machine
overwriting variable ['SUPERFOCUS_DB']
To make your changes take effect please reactivate your environment
[2023-10-10 08:47:31,281 - INFO] SUPER-FOCUS: A tool for agile functional analysis of shotgun metagenomic data
[2023-10-10 08:47:31,282 - INFO] Using /tmp/tmpmq4gqo0o as the temporary directory
Traceback (most recent call last):
  File "/home/wdmays/miniconda3/envs/super-focus/bin/superfocus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/superfocus.py", line 409, in main
    subsystems_translation = get_subsystems(Path(WORK_DIRECTORY, "db/database_PKs.txt"))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/superfocus.py", line 154, in get_subsystems
    with open(translation_file) as database_file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/db/database_PKs.txt'

Do I need to change the location of the databases? I am confused by this error.

**Comment by wittney-m** [comment]
Hi,

I have fixed the previous error but now still have issues with using the databases. This is the new error.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /tmp/tmpt_7akdam
Opening the database... No such file or directory
 [0s]
Error: Error opening file /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/db/static/diamond/90_clusters.db
Diamond blast was terminated by signal 1


 Any other options for getting passed this issue? I have attempted to change the permissions of the files and directory but still no luck.

**Comment by metageni-twist** [comment]
can you send me the listing (ls) of the files at /home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/db/static/diamond/?

**Comment by wittney-m** [comment]
Hi,

I have a folder with the following directories:
100_clusters  
90_clusters  
95_clusters  
98_clusters  

Within each directory is a database. For example in 100_clusters there is 100_clusters.db. file.

**Comment by metageni-twist** [comment]
i see. the error you shared is expecting `/home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/db/static/diamond/90_clusters.db`, but I guess it is `/home/wdmays/miniconda3/envs/super-focus/lib/python3.11/site-packages/superfocus_app/db/db/static/diamond/90_clusters /90_clusters.db` in your directory
